services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: pipo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    restart: always
    depends_on:
      - db
    environment:
      DB_DSN: postgres://postgres:1234@db:5432/pipo?sslmode=disable
      JWT_SECRET: default-secret
      PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    restart: always
    depends_on:
      - app
    ports:
      - "8081:80"

  prometheus:
    image: prom/prometheus:v3.3.1
    restart: always
    depends_on:
      - app
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

volumes:
  pgdata:
  prometheus_data:
